# Workflow to deploy to github Pages
name: Deploy to github Pages

on:
  # Runs on merge to main/master
  merge:
    branches:
      - master
      - workflow

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # sets up node and then runs vite to create dist folder
      - name: buildVite
        uses: actions/setup-node@v3
        with:
          node-version: [16.x]
      - run: npm ci
      - run: npm run viteBuild --if-present
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          #path to dist folder
          path: `./dist`
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 
